version: '3'
services:
  datacose-vue-challenge-service:
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
